### ISSUE TITLE
some question

### ISSUE THREAD

**Issue by wxy-2012** [uulm-mrm/guided-extended-hybrid-astar#5]
hello，I would like to reproduce your code, please tell me which version of ubuntu I am using, and which version of ros2

**Comment by oliver-schumann** [comment]
Hi wxy-2012,

The Dockerfile found in docker/ answers all your questions.
I pulled the following docker
``nvidia/cuda:12.1.0-cudnn8-devel-ubuntu22.04``
Hence, I used Ubuntu22.04.

Afterwards I installed ROS2 Iron with
ros-iron-desktop

If you want to try the code out you can also follow the Instructions in the Readme.md.
Im currently checking if they still work :)

Best wishes
Oliver

**Comment by oliver-schumann** [comment]
I just checked and fixed the docker procedure. You can just follow the instructions in the readme :)
Have Fun with it!

**Comment by wxy-2012** [comment]
I'm sorry to bother you again. I'm a beginner. According to your prompt, I have installed ubuntu22.04 and ros2 iron. What should I do next to replicate your code, or what the process looks like?

**Comment by oliver-schumann** [comment]
Hi wxy-2012,

The simplest way would be to follow the instructions in the Readme.
For this, you don't even need ROS2 Iron and Ubuntu22, as it is automatically installed inside the docker container you run the code in. If you want to run the code directly on your machine without using the docker you must fullfill the prerequisites of the system created by the Dockerfile.

**Comment by wxy-2012** [comment]
I decided to use docker to run your project. Now that I have installed docker in ubuntu20.04, what should I do next
